In [69]:
import pandas as pd

# PYKT处理数据流程

In [70]:
read_file = 'bridge_to_algebra_2006_2007_train.txt'

In [71]:
df = pd.read_table(read_file, low_memory=False)
df.columns, df.shape

(Index(['Row', 'Anon Student Id', 'Problem Hierarchy', 'Problem Name',
        'Problem View', 'Step Name', 'Step Start Time',
        'First Transaction Time', 'Correct Transaction Time', 'Step End Time',
        'Step Duration (sec)', 'Correct Step Duration (sec)',
        'Error Step Duration (sec)', 'Correct First Attempt', 'Incorrects',
        'Hints', 'Corrects', 'KC(SubSkills)', 'Opportunity(SubSkills)'],
       dtype='object'),
 (3679199, 19))

In [72]:
def replace_text(text):
    text = text.replace("_", "####").replace(",", "@@@@")
    return text



#concat problem name & step_name
df["Problem Name"] = df["Problem Name"].apply(replace_text)
df["Step Name"] = df["Step Name"].apply(replace_text)
df["Questions"] = df.apply(lambda x:f"{x['Problem Name']}----{x['Step Name']}",axis=1)

### 删除空值

In [73]:
from datetime import datetime
def change2timestamp(t, hasf=True):
    if hasf:
        timeStamp = datetime.strptime(t, "%Y-%m-%d %H:%M:%S.%f").timestamp() * 1000
    else:
        timeStamp = datetime.strptime(t, "%Y-%m-%d %H:%M:%S").timestamp() * 1000
    return int(timeStamp)

In [74]:
df = df.dropna(subset=["Anon Student Id", "KC(SubSkills)", "Questions", "Correct First Attempt", "First Transaction Time"])
#filter invalid record
df = df[df["Correct First Attempt"].isin([0,1])]
df.loc[:, "First Transaction Time"] = df.loc[:, "First Transaction Time"].apply(lambda t: change2timestamp(t))
df["KC(SubSkills)"] = df["KC(SubSkills)"].apply(replace_text)
df.shape

(1817476, 20)

In [75]:
df.columns

Index(['Row', 'Anon Student Id', 'Problem Hierarchy', 'Problem Name',
       'Problem View', 'Step Name', 'Step Start Time',
       'First Transaction Time', 'Correct Transaction Time', 'Step End Time',
       'Step Duration (sec)', 'Correct Step Duration (sec)',
       'Error Step Duration (sec)', 'Correct First Attempt', 'Incorrects',
       'Hints', 'Corrects', 'KC(SubSkills)', 'Opportunity(SubSkills)',
       'Questions'],
      dtype='object')

### 删除记录数小于3的

In [76]:
# 统计每个 user_id 出现的次数
user_counts = df['Anon Student Id'].value_counts()
# 保留记录数大于或等于3的 user_id
filtered_df = df[df['Anon Student Id'].isin(user_counts[user_counts >= 3].index)]
df = filtered_df

In [77]:
df.shape

(1817474, 20)

In [78]:
df.head()

,Row,Anon Student Id,Problem Hierarchy,Problem Name,Problem View,Step Name,Step Start Time,First Transaction Time,Correct Transaction Time,Step End Time,Step Duration (sec),Correct Step Duration (sec),Error Step Duration (sec),Correct First Attempt,Incorrects,Hints,Corrects,KC(SubSkills),Opportunity(SubSkills),Questions
0,1,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,InitialQuestion,2006-10-05 13:22:59.0,1160025873000,2006-10-05 13:24:44.0,2006-10-05 13:24:44.0,97.667,NaN,97.667,0,1,0,1,Identify larger quantity -- multiplication,1,PICTALG3MU003----InitialQuestion
3,4,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,Bar2,2006-10-05 13:24:44.0,1160025916000,2006-10-05 13:25:16.0,2006-10-05 13:25:16.0,32.000,32.0,NaN,1,0,0,1,Draw larger bar -- multiplication,1,PICTALG3MU003----Bar2
4,5,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,Bar1,2006-10-05 13:25:16.0,1160025921000,2006-10-05 13:25:21.0,2006-10-05 13:25:21.0,5.000,5.0,NaN,1,0,0,1,Draw smaller bar -- multiplication,1,PICTALG3MU003----Bar1
5,6,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,SmallerBar,2006-10-05 13:25:21.0,1160025932000,2006-10-05 13:25:50.0,2006-10-05 13:25:50.0,26.000,NaN,26.000,0,1,0,1,Enter smaller initial in diagram -- given,1,PICTALG3MU003----SmallerBar
6,7,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,LargerBar,2006-10-05 13:25:32.0,1160025935000,2006-10-05 13:26:23.0,2006-10-05 13:26:23.0,36.000,NaN,36.000,0,2,0,1,Enter larger inital in diagram -- calculated,1,PICTALG3MU003----LargerBar

In [79]:
# 假设 df 是你当前的数据框
df = df.drop(columns=['Row'])
df.head()

,Anon Student Id,Problem Hierarchy,Problem Name,Problem View,Step Name,Step Start Time,First Transaction Time,Correct Transaction Time,Step End Time,Step Duration (sec),Correct Step Duration (sec),Error Step Duration (sec),Correct First Attempt,Incorrects,Hints,Corrects,KC(SubSkills),Opportunity(SubSkills),Questions
0,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,InitialQuestion,2006-10-05 13:22:59.0,1160025873000,2006-10-05 13:24:44.0,2006-10-05 13:24:44.0,97.667,NaN,97.667,0,1,0,1,Identify larger quantity -- multiplication,1,PICTALG3MU003----InitialQuestion
3,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,Bar2,2006-10-05 13:24:44.0,1160025916000,2006-10-05 13:25:16.0,2006-10-05 13:25:16.0,32.000,32.0,NaN,1,0,0,1,Draw larger bar -- multiplication,1,PICTALG3MU003----Bar2
4,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,Bar1,2006-10-05 13:25:16.0,1160025921000,2006-10-05 13:25:21.0,2006-10-05 13:25:21.0,5.000,5.0,NaN,1,0,0,1,Draw smaller bar -- multiplication,1,PICTALG3MU003----Bar1
5,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,SmallerBar,2006-10-05 13:25:21.0,1160025932000,2006-10-05 13:25:50.0,2006-10-05 13:25:50.0,26.000,NaN,26.000,0,1,0,1,Enter smaller initial in diagram -- given,1,PICTALG3MU003----SmallerBar
6,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,LargerBar,2006-10-05 13:25:32.0,1160025935000,2006-10-05 13:26:23.0,2006-10-05 13:26:23.0,36.000,NaN,36.000,0,2,0,1,Enter larger inital in diagram -- calculated,1,PICTALG3MU003----LargerBar

In [80]:
df.columns

Index(['Anon Student Id', 'Problem Hierarchy', 'Problem Name', 'Problem View',
       'Step Name', 'Step Start Time', 'First Transaction Time',
       'Correct Transaction Time', 'Step End Time', 'Step Duration (sec)',
       'Correct Step Duration (sec)', 'Error Step Duration (sec)',
       'Correct First Attempt', 'Incorrects', 'Hints', 'Corrects',
       'KC(SubSkills)', 'Opportunity(SubSkills)', 'Questions'],
      dtype='object')

In [81]:
# 将 "Correct First Attempt" 列重命名为 "correct"
df = df.rename(columns={"Correct First Attempt": "correct"})

In [82]:
df['correct'].unique()

array([0, 1])

In [83]:
df.columns

Index(['Anon Student Id', 'Problem Hierarchy', 'Problem Name', 'Problem View',
       'Step Name', 'Step Start Time', 'First Transaction Time',
       'Correct Transaction Time', 'Step End Time', 'Step Duration (sec)',
       'Correct Step Duration (sec)', 'Error Step Duration (sec)', 'correct',
       'Incorrects', 'Hints', 'Corrects', 'KC(SubSkills)',
       'Opportunity(SubSkills)', 'Questions'],
      dtype='object')

In [84]:
df.head()

,Anon Student Id,Problem Hierarchy,Problem Name,Problem View,Step Name,Step Start Time,First Transaction Time,Correct Transaction Time,Step End Time,Step Duration (sec),Correct Step Duration (sec),Error Step Duration (sec),correct,Incorrects,Hints,Corrects,KC(SubSkills),Opportunity(SubSkills),Questions
0,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,InitialQuestion,2006-10-05 13:22:59.0,1160025873000,2006-10-05 13:24:44.0,2006-10-05 13:24:44.0,97.667,NaN,97.667,0,1,0,1,Identify larger quantity -- multiplication,1,PICTALG3MU003----InitialQuestion
3,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,Bar2,2006-10-05 13:24:44.0,1160025916000,2006-10-05 13:25:16.0,2006-10-05 13:25:16.0,32.000,32.0,NaN,1,0,0,1,Draw larger bar -- multiplication,1,PICTALG3MU003----Bar2
4,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,Bar1,2006-10-05 13:25:16.0,1160025921000,2006-10-05 13:25:21.0,2006-10-05 13:25:21.0,5.000,5.0,NaN,1,0,0,1,Draw smaller bar -- multiplication,1,PICTALG3MU003----Bar1
5,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,SmallerBar,2006-10-05 13:25:21.0,1160025932000,2006-10-05 13:25:50.0,2006-10-05 13:25:50.0,26.000,NaN,26.000,0,1,0,1,Enter smaller initial in diagram -- given,1,PICTALG3MU003----SmallerBar
6,2719gmbyqtjd,"Unit PICTURE-ALGEBRA-1, Section PICTURE-ALGEBR...",PICTALG3MU003,1,LargerBar,2006-10-05 13:25:32.0,1160025935000,2006-10-05 13:26:23.0,2006-10-05 13:26:23.0,36.000,NaN,36.000,0,2,0,1,Enter larger inital in diagram -- calculated,1,PICTALG3MU003----LargerBar

In [85]:
df['Corrects'].unique()

array([ 1,  0,  2,  3,  4,  5,  6, 10,  7,  9,  8, 11, 12, 18, 13, 14, 15,
       16, 28])

In [86]:
df.shape

(1817474, 19)

In [87]:
df.columns

Index(['Anon Student Id', 'Problem Hierarchy', 'Problem Name', 'Problem View',
       'Step Name', 'Step Start Time', 'First Transaction Time',
       'Correct Transaction Time', 'Step End Time', 'Step Duration (sec)',
       'Correct Step Duration (sec)', 'Error Step Duration (sec)', 'correct',
       'Incorrects', 'Hints', 'Corrects', 'KC(SubSkills)',
       'Opportunity(SubSkills)', 'Questions'],
      dtype='object')

In [88]:
# 将处理后的数据保存为 CSV 文件
# df.to_csv('../data/bridge2006_csv/pykt_all_data.csv', index=False)

### 以上数据与PYKT数据一致

### 特征

In [89]:
# # 初始化列分类
# numerical_features = [
#     'Step Duration (sec)',  # 步骤持续时间
#     'Correct Step Duration (sec)',  # 正确步骤持续时间
#     'Error Step Duration (sec)',  # 错误步骤持续时间
#     'Step Start Time',  # 步骤开始时间（可以作为时间戳处理）
#     'First Transaction Time',  # 第一次操作时间
#     'Correct Transaction Time',  # 正确操作时间
#     'Step End Time',  # 步骤结束时间
# ]

# categorical_features = [
#     'Anon Student Id',  # 学生匿名ID
#     'Problem Hierarchy',  # 问题层次结构
#     'Problem Name',  # 问题名称
#     'Problem View',  # 问题查看次数
#     'Step Name',  # 步骤名称
#     'KC(SubSkills)',
#     'Opportunity(SubSkills)',  # 知识点机会次数
#     'Questions' , # 问题相关信息
#     'Incorrects',  # 错误次数
#     'Hints',  # 请求提示的次数
#     'Corrects'
# ]

# # 标签特征
# label_feature = 'correct'  # 标签（即是否正确）

重新选择特征"Anon Student Id", "KC(SubSkills)", "Questions", "Correct First Attempt", "First Transaction Time"

In [90]:
# 初始化列分类
numerical_features = [
    'First Transaction Time',  # 第一次操作时间
   
]

categorical_features = [
    'Anon Student Id',  # 学生匿名ID
    'KC(SubSkills)',
    'Questions' , # 问题相关信息
    'Hints',  # 请求提示的次数
]

# 标签特征
label_feature = 'correct'  # 标签（即是否正确）

In [91]:
# 选择需要保留的列
columns_to_keep = ['First Transaction Time', 'Anon Student Id', 'KC(SubSkills)', 'Questions' , 'Hints', 'correct']

# # 筛选保留指定列
df = df[columns_to_keep]
df.columns

Index(['First Transaction Time', 'Anon Student Id', 'KC(SubSkills)',
       'Questions', 'Hints', 'correct'],
      dtype='object')

归一化，去除极端值

In [92]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import numpy as np

# 将数值特征转换为数值类型
for col in numerical_features:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 对数值特征进行归一化
scaler = MinMaxScaler()
df[numerical_features] = scaler.fit_transform(df[numerical_features])

# 观察归一化后的分布
for col in numerical_features:
    print(f"{col} max:", df[col].max(), "min:", df[col].min())

# 去除极端值，将值限制在 [0, 1] 范围内
for col in numerical_features:
    df[col] = np.clip(df[col], 0, 1)

# 处理类别特征：将其转换为整数编码
integer_encoded_features = {}
for col in categorical_features:
    df[col] = df[col].fillna('Unknown').astype(str)
    label_encoder = LabelEncoder()
    df[col] = label_encoder.fit_transform(df[col])
    integer_encoded_features[col] = {
        'encoder': label_encoder,
        'n_unique': len(label_encoder.classes_)
    }

# 处理标签特征：转换为整数编码
df[label_feature] = df[label_feature].fillna('Unknown').astype(str)
label_encoder = LabelEncoder()
df[label_feature] = label_encoder.fit_transform(df[label_feature])

First Transaction Time max: 1.0 min: 0.0

In [93]:
df['correct'].unique()

array([0, 1])

In [94]:
# 计算每个唯一值的比例
value_counts = df['correct'].value_counts(normalize=True)

# 输出结果
print(value_counts)

1    0.832151
0    0.167849
Name: correct, dtype: float64

### 划分数据集

In [95]:
from sklearn.model_selection import train_test_split
# 按照用户划分 80% 训练+验证集，20% 测试集
train_val_data, test_data = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)
# 你可以根据需求继续对 train_val_data 进一步划分为训练集和验证集
train_data, val_data = train_test_split(train_val_data, test_size=0.2, random_state=42)

In [96]:
# 保存划分后的数据集
train_data.to_csv("../data/bridge2006_csv/train.csv", index=False)
val_data.to_csv("../data/bridge2006_csv/valid.csv", index=False)
test_data.to_csv("../data/bridge2006_csv/test.csv", index=False)

In [97]:
train_data.columns

Index(['First Transaction Time', 'Anon Student Id', 'KC(SubSkills)',
       'Questions', 'Hints', 'correct'],
      dtype='object')

In [98]:
train_data.shape

(1163183, 6)

In [99]:
val_data.columns

Index(['First Transaction Time', 'Anon Student Id', 'KC(SubSkills)',
       'Questions', 'Hints', 'correct'],
      dtype='object')

In [100]:
test_data.columns

Index(['First Transaction Time', 'Anon Student Id', 'KC(SubSkills)',
       'Questions', 'Hints', 'correct'],
      dtype='object')